server:
  port: 8081 # Auth service üçün standart port

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tripway_auth_db
    username: postgres
    password: Huseyn007
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: komik958@gmail.com
    password: xxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # Bu, e-maillərin şifrələnərək getməsini təmin edir

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server-ə qeydiyyat ünvanı
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX # Biletə vurulan gizli möhür
  expiration: 86400000 # Access Token vaxtı: 1 gün (ms ilə)
  refresh-expiration: 604800000 # Refresh Token vaxtı: 7 gün (ms ilə)

logging:
  level:
    org.springframework.security: TRACE

